/*!
 * Hero Carousel - jQuery Plugin
 *
 * Copyright (c) 2011 Paul Welsh
 *
 * Version: 1.3 (26/05/2011)
 *
 * Dual licensed under the MIT and GPL licenses:
 *   http://www.opensource.org/licenses/mit-license.php
 *   http://www.gnu.org/licenses/gpl.html
 */jQuery.fn.heroCarousel=function(e){e=jQuery.extend({autoPlay:!1,animationSpeed:1e3,navigation:!0,easing:"",timeout:5e3,pause:!0,pauseOnNavHover:!0,prevText:"Previous",nextText:"Next",css3pieFix:!1,currentClass:"current",onLoad:function(){},onStart:function(){},onComplete:function(){}},e);jQuery.browser.msie&&parseFloat(jQuery.browser.version)<7&&(e.animationSpeed=0);return this.each(function(){var t=jQuery(this),n=t.children();currentItem=1;childWidth=n.width()+52;childHeight=n.height();if(n.length>2){n.each(function(t){e.itemClass&&jQuery(this).addClass(e.itemClass)});n.filter(":first").addClass(e.currentClass).before(n.filter(":last"));var r=Math.round(childWidth*t.children().length),i="-"+Math.round(childWidth+Math.round(childWidth/2))+"px";t.addClass("hero-carousel-container").css({position:"relative",overflow:"hidden",left:"50%",top:0,"margin-left":i,height:childHeight,width:r});t.before('<ul class="hero-carousel-nav"><li class="prev"><a href="#">'+e.prevText+'</a></li><li class="next"><a href="#">'+e.nextText+"</a></li></ul>");var s=t.prev(".hero-carousel-nav"),o;if(e.timeout>0){var u=!1;e.pause&&t.hover(function(){u=!0},function(){u=!1});e.pauseOnNavHover&&s.hover(function(){u=!0},function(){u=!1});function a(){return!1}o=window.setInterval(a,e.timeout)}s.find("a").data("disabled",!1).click(function(n){n.preventDefault();var r=jQuery(this),i=r.parent().hasClass("prev"),u=t.children();if(r.data("disabled")===!1){e.onStart(t,s,u.eq(currentItem),e);i?f(u.filter(":last"),"previous"):f(u.filter(":first"),"next");r.data("disabled",!0);setTimeout(function(){r.data("disabled",!1)},e.animationSpeed+200);if(e.timeout>0){window.clearInterval(o);o=window.setInterval(a,e.timeout)}}});function f(n,s){var o=parseFloat(t.position().left),u=parseFloat(t.css("margin-left"));if(s==="previous"){n.before(n.clone().addClass("carousel-clone"));t.prepend(n);var a=Math.round(u-childWidth),f="+="}else{n.after(n.clone().addClass("carousel-clone"));t.append(n);var a=i,f="-="}e.css3pieFix&&l(jQuery(".carousel-clone"));t.css({left:o,width:Math.round(r+childWidth),"margin-left":a}).animate({left:f+childWidth},e.animationSpeed,e.easing,function(){t.css({left:"50%",width:r,"margin-left":u});jQuery(".carousel-clone").remove();c()})}function l(e){var t=e.attr("_pieId");t&&e.attr("_pieId",t+"_cloned");e.find("*[_pieId]").each(function(e,t){var n=$(t).attr("_pieId");$(t).attr("_pieId",n+"_cloned")})}function c(){var n=t.children();n.removeClass(e.currentClass).eq(currentItem).addClass(e.currentClass);e.onComplete(t,t.prev(".hero-carousel-nav"),n.eq(currentItem),e)}jQuery.browser.msie&&s.find("a").attr("hideFocus","true");e.onLoad(t,s,t.children().eq(currentItem),e)}})};

